### ISSUE TITLE
Add Travis CI for all libraries

### ISSUE THREAD

**Issue by Hywan** [hoaproject/Central#36]
As discussed in the last Hoa Virtual Meeting (https://github.com/hoaproject/ActionBoard/issues/26), we are going to move our CI to Travis.

### Progression

  * [ ] `Acl`,
  * [ ] `Bench`,
  * [ ] `Cache`,
  * [ ] `Cli`,
  * [ ] `Compiler`,
  * [ ] `Consistency`,
  * [ ] `Console`,
  * [ ] `Core`,
  * [ ] `Database`,
  * [ ] `Devtools`,
  * [ ] `Dispatcher`,
  * [ ] `Dns`,
  * [ ] `Event`,
  * [ ] `Eventsource`,
  * [ ] `Exception`,
  * [ ] `Fastcgi`,
  * [ ] `File`,
  * [ ] `Graph`,
  * [ ] `Http`,
  * [ ] `Irc`,
  * [ ] `Iterator`,
  * [ ] `Json`,
  * [ ] `Locale`,
  * [ ] `Log`,
  * [ ] `Mail`,
  * [ ] `Math`,
  * [ ] `Memory`,
  * [ ] `Mime`,
  * [ ] `Model`,
  * [ ] `Notification`,
  * [ ] `Praspel`,
  * [ ] `Promise`,
  * [ ] `Protocol`,
  * [ ] `Prototype`,
  * [ ] `Realdom`,
  * [ ] `Regex`,
  * [ ] `Registry`,
  * [ ] `Router`,
  * [ ] `Ruler`,
  * [ ] `Serialize`,
  * [ ] `Session`,
  * [ ] `Socket`,
  * [ ] `Stream`,
  * [ ] `String`,
  * [ ] `Stringbuffer`,
  * [ ] `Test`,
  * [ ] `Translate`,
  * [ ] `Tree`,
  * [ ] `Ustring`,
  * [ ] `View`,
  * [ ] `Visitor`,
  * [ ] `Websocket`,
  * [ ] `Worker`,
  * [ ] `Xml`,
  * [ ] `Xmlrpc`,
  * [ ] `Xyl`,
  * [ ] `Zformat`,
  * [ ] `Zombie`,
  * [ ] ` `.

**Comment by Hywan** [comment]
Issue template:
```
Address https://github.com/hoaproject/Central/issues/36.
```

Travis template:
```
language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm
  - hhvm-nightly
os:
  - linux
  - osx
matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
    - php: hhvm-nightly
  fast_finish: true
notifications:
  irc: "chat.freenode.net#hoaproject"
sudo: false
script:
  - composer install
  - vendor/bin/hoa test:run
```

Everything is already configured on Travis' side.
